export const ERROR_CODES = {
  // 400
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  INVALID_CODE: 'INVALID_CODE',
  CODE_EXPIRED: 'CODE_EXPIRED',
  MAX_ATTEMPTS_EXCEEDED: 'MAX_ATTEMPTS_EXCEEDED',
  // 401
  UNAUTHORIZED: 'UNAUTHORIZED',
  // 403
  FORBIDDEN: 'FORBIDDEN',
  SUBSCRIPTION_LIMIT_REACHED: 'SUBSCRIPTION_LIMIT_REACHED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  // 404
  NOT_FOUND: 'NOT_FOUND',
  // 409
  CONFLICT: 'CONFLICT',
  REGISTRATION_PENDING: 'REGISTRATION_PENDING',
  ENCOUNTER_LOCKED: 'ENCOUNTER_LOCKED',
  PATIENT_HAS_OPEN_VISIT: 'PATIENT_HAS_OPEN_VISIT',
  PREGNANCY_ACTIVE: 'PREGNANCY_ACTIVE',
  PREGNANCY_ACTIVE_REQUIRES_CLOSE: 'PREGNANCY_ACTIVE_REQUIRES_CLOSE',
  SURGICAL_ACTIVE: 'SURGICAL_ACTIVE',
  // 412
  STALE_VERSION: 'STALE_VERSION',
  // 422
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  // 429
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  // 500
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
