export {
  CLINICAL_EVENTS,
  type PatientHistoryUpdatedEvent,
  type EncounterAmendedEvent,
  type PregnancyBookedEvent,
  type PregnancyRiskLevelChangedEvent,
  type VisitPregnancyRecordUpdatedEvent,
  type PregnancyClosedEvent,
  type SurgicalBookedEvent,
  type SurgicalClosedEvent,
  type JourneyClinicalUpdatedEvent,
  type JourneyCarePathSetEvent,
  type VisitExaminationUpdatedEvent,
  type InvestigationResultUploadedEvent,
  type InvestigationReviewedEvent,
} from './clinical-events';
